// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:easy_localization/easy_localization.dart';
import 'package:ez_shop_sync/res/generated/locale.g.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/string_locale.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/unit_type.dart';
import 'package:ez_shop_sync/src/data/repository/store/store_repository.dart';
import 'package:ez_shop_sync/src/models/screen_mode.dart';
import 'package:ez_shop_sync/src/pages/_app/app_cubit.dart';
import 'package:ez_shop_sync/src/widgets/buttons/button_widget.dart';
import 'package:ez_shop_sync/src/widgets/text_form_field/text_form_field_ui_widget.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';

class BottomSheetCreateUnitTypeSuccess {
  final UnitType unitType;

  const BottomSheetCreateUnitTypeSuccess(this.unitType);
}

class BottomSheetCreateUniTypeWidget extends StatefulWidget {
  final UnitType? unitType;

  const BottomSheetCreateUniTypeWidget({super.key, this.unitType});

  @override
  _BottomSheetCreateUniTypeWidgetState createState() => _BottomSheetCreateUniTypeWidgetState();
}

class _BottomSheetCreateUniTypeWidgetState extends State<BottomSheetCreateUniTypeWidget> {
  final _thTextController = TextEditingController();
  final _enTextController = TextEditingController();
  final _thShortTextController = TextEditingController();
  final _enShortTextController = TextEditingController();
  final storeRepository = GetIt.I<StoreRepository>();
  final appCubit = GetIt.I<AppCubit>();
  String? errorMessage;
  bool isLoading = false;

  ScreenMode screenMode = ScreenMode.create;

  bool get isDisabled {
    if (screenMode == ScreenMode.create) {
      return _enTextController.text.isEmpty ||
          _thTextController.text.isEmpty ||
          _enShortTextController.text.isEmpty ||
          _thShortTextController.text.isEmpty ||
          isLoading;
    } else if (screenMode == ScreenMode.edit) {
      return (_thTextController.text == widget.unitType?.name.th &&
              _enTextController.text == widget.unitType?.name.en &&
              _thShortTextController.text == widget.unitType?.shortName.th &&
              _enShortTextController.text == widget.unitType?.shortName.en) ||
          isLoading;
    }

    return false;
  }

  @override
  void initState() {
    if (widget.unitType != null) {
      _thTextController.text = widget.unitType?.name.th ?? '';
      _enTextController.text = widget.unitType?.name.en ?? '';
      _thShortTextController.text = widget.unitType?.shortName.th ?? '';
      _enShortTextController.text = widget.unitType?.shortName.en ?? '';
      screenMode = ScreenMode.edit;
    }
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(left: 16.0, right: 16, bottom: 8),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            LocaleKeys.createUnitType.tr(),
            style: Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
          ),
          SizedBox(height: 12),
          SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Expanded(
                      flex: 8,
                      child: AppTextFormFieldUiWidget(
                        controller: _enTextController,
                        label: LocaleKeys.locales_en.tr(),
                        hintText: LocaleKeys.locales_enHint.tr(),
                        onChanged: (value) {
                          setState(() {});
                        },
                      ),
                    ),
                    SizedBox(width: 8),
                    Expanded(
                      flex: 4,
                      child: AppTextFormFieldUiWidget(
                        controller: _enShortTextController,
                        hintText: LocaleKeys.locales_enShortHint.tr(),
                        onChanged: (value) {
                          setState(() {});
                        },
                      ),
                    ),
                  ],
                ),
                const Divider(color: Colors.grey),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    Expanded(
                      flex: 8,
                      child: AppTextFormFieldUiWidget(
                        controller: _thTextController,
                        label: LocaleKeys.locales_th.tr(),
                        hintText: LocaleKeys.locales_thHint.tr(),
                        onChanged: (value) {
                          setState(() {});
                        },
                      ),
                    ),
                    SizedBox(width: 8),
                    Expanded(
                      flex: 4,
                      child: AppTextFormFieldUiWidget(
                        controller: _thShortTextController,
                        hintText: LocaleKeys.locales_thShortHint.tr(),
                        onChanged: (value) {
                          setState(() {});
                        },
                      ),
                    ),
                  ],
                ),
                if (errorMessage?.isNotEmpty ?? false)
                  Text(errorMessage ?? '', style: Theme.of(context).textTheme.bodyMedium?.copyWith(color: Colors.red)),
              ],
            ),
          ),
          ButtonWidget(
            isLoading: isLoading,
            margin: const EdgeInsets.only(top: 16),
            label: screenMode == ScreenMode.create ? LocaleKeys.button_submit.tr() : LocaleKeys.button_save.tr(),
            onPressed:
                isDisabled
                    ? null
                    : () async {
                      if (screenMode == ScreenMode.create) {
                        doCreate();
                      } else if (screenMode == ScreenMode.edit) {
                        doSave();
                      }
                    },
          ),
        ],
      ),
    );
  }

  void doCreate() async {
    final payload = UnitType(
      name: StringLocale(en: _enTextController.text, th: _thTextController.text),
      shortName: StringLocale(en: _enShortTextController.text, th: _thShortTextController.text),
    );
    setState(() {
      isLoading = true;
    });
    final result = await storeRepository.createUnitTypes(appCubit.request(payload));
    setState(() {
      isLoading = false;
    });
    result.when(
      success: (response) {
        appCubit.addUnitTypes(response);
        Navigator.of(context).pop(response);
      },
      failure: (error) {
        setState(() {
          errorMessage = error.errorType.label;
        });
      },
    );
  }

  void doSave() async {
    final payload = UnitType(
      id: widget.unitType?.id,
      name: StringLocale(en: _enTextController.text.trim(), th: _thTextController.text.trim()),
      shortName: StringLocale(en: _enShortTextController.text.trim(), th: _thShortTextController.text.trim()),
      info: widget.unitType?.info,
    );

    setState(() {
      isLoading = true;
    });
    final result = await storeRepository.updateUnitType(appCubit.request(payload));

    setState(() {
      isLoading = false;
    });

    result.when(
      success: (response) {
        Navigator.of(context).pop(response);
      },
      failure: (error) {
        setState(() {
          errorMessage = error.errorType.label;
        });
      },
    );
  }
}
