// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

import 'package:ez_shop_sync/src/models/base_object.dart';

part 'base_hive_data.g.dart';

@HiveType(typeId: 17)
@JsonSerializable(explicitToJson: true)
class BaseHiveData extends BaseObject {
  @HiveField(1, defaultValue: null)
  String? storeId;

  @HiveField(2, defaultValue: null)
  String? branchId;

  @HiveField(3, defaultValue: null)
  String? createBy;

  @HiveField(4, defaultValue: null)
  String? updateBy;

  @HiveField(5, defaultValue: null)
  dynamic createAt;

  @HiveField(6, defaultValue: null)
  dynamic updateAt;

  @HiveField(7, defaultValue: null)
  dynamic syncDatetime;

  BaseHiveData({
    this.storeId,
    this.branchId,
    this.createBy,
    this.updateBy,
    required this.createAt,
    required this.updateAt,
    this.syncDatetime,
  });

  DateTime get createAtDateTime => (createAt as Timestamp).toDate();
  DateTime get updateAtDateTime => (updateAt as Timestamp).toDate();
  DateTime get syncDatetimeDateTime => (syncDatetime as Timestamp).toDate();

  factory BaseHiveData.fromJson(Map<String, dynamic> json) => _$BaseHiveDataFromJson(json);

  @override
  Map<String, dynamic> toJson() => _$BaseHiveDataToJson(this);
}
