// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

import 'package:ez_shop_sync/src/models/base_object.dart';

part 'base_hive_data.g.dart';

@HiveType(typeId: 17)
@JsonSerializable(explicitToJson: true)
class BaseHiveData extends BaseObject {
  @HiveField(1, defaultValue: null)
  dynamic createAt;

  @HiveField(2, defaultValue: null)
  dynamic createBy;

  @HiveField(3, defaultValue: null)
  dynamic updateAt;

  @HiveField(4, defaultValue: null)
  String? updateBy;

  @HiveField(5, defaultValue: null)
  DateTime? syncDatetime;

  BaseHiveData({
    required this.createAt,
    this.createBy,
    required this.updateAt,
    this.updateBy,
    this.syncDatetime,
  });

  factory BaseHiveData.fromJson(Map<String, dynamic> json) =>
      _$BaseHiveDataFromJson(json);

  @override
  Map<String, dynamic> toJson() => _$BaseHiveDataToJson(this);
}
