// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:hive/hive.dart';

import 'package:ez_shop_sync/src/data/dto/hive_object/product.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';

part 'cart_item.g.dart';

@HiveType(typeId: 9)
class CartItem extends BaseHiveObject {
  @HiveField(7)
  Product? product;

  CartItem({
    required super.id,
    required this.product,
  });

  CartItem copyWith({
    String? id,
    Product? product,
  }) {
    return CartItem(
      id: id ?? super.id,
      product: product ?? this.product,
    );
  }
}
