// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/order_item.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'cart.g.dart';

@HiveType(typeId: 8)
@JsonSerializable(explicitToJson: true)
class Cart extends BaseHiveObject {
  @HiveField(7)
  String userId;

  @HiveField(8)
  String storeId;

  @HiveField(9, defaultValue: [])
  List<OrderItem> cartItems;

  Cart({
    super.id,
    BaseHiveData? super.info,
    required this.cartItems,
    required this.storeId,
    required this.userId,
  });

  factory Cart.fromJson(Map<String, dynamic> json) => _$CartFromJson(json);

  Map<String, dynamic> toJson() => _$CartToJson(this);
}
