// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/cart_item.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:hive/hive.dart';

part 'cart.g.dart';

@HiveType(typeId: 8)
class Cart extends BaseHiveObject {
  @HiveField(7)
  String userId;

  @HiveField(8)
  String storeId;

  @HiveField(9, defaultValue: [])
  List<CartItem> cartItems;

  Cart({
    required super.id,
    super.createDate,
    super.createBy,
    super.updateDate,
    super.updateBy,
    super.syncDatetime,
    required this.cartItems,
    required this.storeId,
    required this.userId,
  });

  @override
  String toString() => 'Cart(id: ${super.id} userId: $userId, storeId: $storeId, productItems: $cartItems)';
}
