// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *

import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:hive/hive.dart';

import 'package:ez_shop_sync/src/data/dto/hive_object/product.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:json_annotation/json_annotation.dart';

part 'order_item.g.dart';

@HiveType(typeId: 9)
@JsonSerializable(explicitToJson: true)
class OrderItem extends BaseHiveObject {
  @HiveField(7)
  Product? product;

  @HiveField(8)
  String? note;

  @HiveField(9)
  num? cost;

  OrderItem({super.id, super.info, required this.product, this.note, this.cost});

  OrderItem copyWith({String? id, Product? product, num? cost}) {
    return OrderItem(id: id ?? super.id, product: product ?? this.product, cost: cost ?? this.cost);
  }

  factory OrderItem.fromJson(Map<String, dynamic> json) => _$OrderItemFromJson(json);

  Map<String, dynamic> toJson() => _$OrderItemToJson(this);
}
