// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:hive/hive.dart';

import 'package:ez_shop_sync/src/data/dto/hive_object/product.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';

part 'order_item.g.dart';

@HiveType(typeId: 9)
class OrderItem extends BaseHiveObject {
  @HiveField(7)
  Product? product;

  @HiveField(8)
  String? note;

  OrderItem({
    required super.id,
    required this.product,
    this.note,
  });

  OrderItem copyWith({
    String? id,
    Product? product,
  }) {
    return OrderItem(
      id: id ?? super.id,
      product: product ?? this.product,
    );
  }
}
