// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/models/base_object.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'product_type.g.dart';

@JsonSerializable(explicitToJson: true)
@HiveType(typeId: 18)
class ProductType extends BaseObject {
  @HiveField(1)
  dynamic id;

  @HiveField(2)
  final String name;

  @HiveField(3)
  final num? price;

  @HiveField(4)
  final num? quantity;

  @HiveField(5)
  final String? image;

  @HiveField(6)
  final String? desc;

  ProductType({
    this.id,
    this.name = '',
    this.price = 0,
    this.quantity = 0,
    required this.image,
    this.desc,
  });

  factory ProductType.fromJson(Map<String, dynamic> json) => _$ProductTypeFromJson(json);

  Map<String, dynamic> toJson() => _$ProductTypeToJson(this);
}
