// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'dart:math';

import 'package:ez_shop_sync/src/data/dto/hive_object/unit_type.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product_config.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product_type.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:ez_shop_sync/src/utils/extensions/num_extension.dart';
import 'package:ez_shop_sync/src/utils/extensions/object_extension.dart';
import 'package:ez_shop_sync/src/utils/extensions/string_extensions.dart';

part 'product.g.dart';

@HiveType(typeId: 1)
@JsonSerializable(explicitToJson: true)
class Product extends BaseHiveObject {
  @HiveField(7)
  String name;

  @HiveField(8, defaultValue: null)
  String? description;

  @HiveField(9, defaultValue: null)
  String? category;

  @HiveField(10, defaultValue: null)
  String? brand;

  @HiveField(11, defaultValue: null)
  String? imageUrl;

  @HiveField(12, defaultValue: null)
  List<String>? imagesUrl;

  @HiveField(13, defaultValue: null)
  String? imageThumbnail;

  @HiveField(14, defaultValue: {})
  Map<String, dynamic>? attributes;

  @HiveField(15, defaultValue: [])
  List<String>? tag;

  @HiveField(16, defaultValue: ProductStatus.undefined)
  ProductStatus status;

  @HiveField(17)
  String storeId;

  @HiveField(18, defaultValue: null)
  num? quantity;

  @HiveField(19, defaultValue: null)
  String ownerId;

  @HiveField(20, defaultValue: null)
  String? priceSelected;

  @HiveField(21, defaultValue: null)
  ProductConfig? config;

  @HiveField(22, defaultValue: null)
  List<ProductType>? productTypeList;

  @HiveField(23, defaultValue: null)
  UnitType? unitType;

  num? get allQuantity => productTypeList?.fold(0, (sum, item) => (sum ?? 0) + (item.quantity ?? 0));

  String? get productTypeSelectDisplay => productTypeList?.firstWhere((e) => e.id == priceSelected).name;
  Product({
    super.id,
    BaseHiveData? super.info,
    required this.name,
    this.description,

    // this.priceCategories,
    this.category,
    this.brand,
    this.imageUrl,
    this.imagesUrl,
    this.imageThumbnail,
    this.attributes,
    this.tag,
    required this.storeId,
    required this.status,
    this.quantity,
    required this.ownerId,
    this.priceSelected,
    this.productTypeList,
    this.unitType,
  });

  List<num>? get priceRange => productTypeList?.map((e) => e.price ?? 0).toList() ?? [];

  num? get minValue => priceRange?.reduce((a, b) => a < b ? a : b) ?? 0;
  num? get maxValue => priceRange?.reduce((a, b) => a > b ? a : b) ?? 0;

  // num
  String get priceStringDisplay =>
      (productTypeList?.isEmpty ?? true) || (priceRange?.isEmpty ?? true)
          ? ''.elseDisplay().prefixCurrency()
          : (priceRange?.length ?? false) == 1
          ? priceRange?.first.toString().prefixCurrency() ?? ''.elseDisplay()
          : '${minValue?.prefixCurrency()} - ${maxValue?.prefixCurrency()}';

  num? get priceCurrentSelected =>
      (productTypeList?.where((mapEntry) => mapEntry.id == priceSelected).firstOrNull?.price ?? 0) * (quantity ?? 0);

  factory Product.fromJson(Map<String, dynamic> json) => _$ProductFromJson(json);

  Map<String, dynamic> toJson() => _$ProductToJson(this);

  Product copyWith({
    String? name,
    String? description,
    String? category,
    String? brand,
    String? imageUrl,
    List<String>? imagesUrl,
    String? imageThumbnail,
    Map<String, dynamic>? attributes,
    List<String>? tag,
    String? storeId,
    num? quantity,
    String? ownerId,
    String? priceSelected,
    List<ProductType>? productTypeList,
    ProductStatus? status,
    BaseHiveData? info,
    UnitType? unitType,
  }) {
    return Product(
      id: super.id,
      name: name ?? this.name,
      description: description ?? this.description,
      category: category ?? this.category,
      brand: brand ?? this.brand,
      imageUrl: imageUrl ?? this.imageUrl,
      imagesUrl: imagesUrl ?? this.imagesUrl,
      imageThumbnail: imageThumbnail ?? this.imageThumbnail,
      attributes: attributes ?? this.attributes,
      tag: tag ?? this.tag,
      storeId: storeId ?? this.storeId,
      quantity: quantity ?? this.quantity,
      ownerId: ownerId ?? this.ownerId,
      priceSelected: priceSelected ?? this.priceSelected,
      productTypeList: productTypeList ?? this.productTypeList,
      status: status ?? this.status,
      info: info ?? this.info,
      unitType: unitType ?? this.unitType,
    );
  }
}

@HiveType(typeId: 2)
enum ProductStatus {
  @HiveField(0)
  active,
  @HiveField(1)
  inactive,
  @HiveField(2)
  discontinued,
  @HiveField(3)
  outOfStock,
  @HiveField(4)
  undefined;

  static ProductStatus fromString(String? value) {
    switch (value) {
      case 'active':
        return ProductStatus.active;
      case 'inactive':
        return ProductStatus.inactive;
      case 'discontinued':
        return ProductStatus.discontinued;
      case 'outOfStock':
        return ProductStatus.outOfStock;

      default:
        return ProductStatus.undefined;
    }
  }
}
