// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product_config.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product_type.dart';
import 'package:hive/hive.dart';

import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:ez_shop_sync/src/utils/extensions/num_extension.dart';
import 'package:ez_shop_sync/src/utils/extensions/object_extension.dart';
import 'package:ez_shop_sync/src/utils/extensions/string_extensions.dart';
import 'package:json_annotation/json_annotation.dart';

part 'product.g.dart';

@HiveType(typeId: 1)
@JsonSerializable(explicitToJson: true)
class Product extends BaseHiveObject {
  @HiveField(7)
  String name;

  @HiveField(8, defaultValue: null)
  String? description;

  @HiveField(9, defaultValue: null)
  String? category;

  @HiveField(10, defaultValue: null)
  String? brand;

  @HiveField(11, defaultValue: null)
  List<String>? imagesPath;

  @HiveField(12, defaultValue: null)
  String? imageThumbnail;

  @HiveField(13, defaultValue: {})
  Map<String, dynamic>? attributes;

  @HiveField(14, defaultValue: [])
  List<String>? tag;

  @HiveField(15, defaultValue: ProductStatus.undefined)
  ProductStatus status;

  @HiveField(16)
  String storeId;

  @HiveField(17, defaultValue: null)
  num? quantity;

  @HiveField(18, defaultValue: null)
  String ownerId;

  @HiveField(19, defaultValue: null)
  String? priceSelected;

  @HiveField(20, defaultValue: null)
  ProductConfig? config;

  @HiveField(21, defaultValue: null)
  List<ProductType>? productTypeList;

  num? get allQuantity => productTypeList?.fold(
      0, (sum, item) => (sum ?? 0) + (item.quantity ?? 0));

  String? get productTypeSelectDisplay =>
      productTypeList?.firstWhere((e) => e.id == priceSelected).name;
  Product({
    super.id,
    BaseHiveData? super.info,
    required this.name,
    this.description,
    // this.priceCategories,
    this.category,
    this.brand,
    this.imagesPath,
    this.imageThumbnail,
    this.attributes,
    this.tag,
    required this.storeId,
    required this.status,
    this.quantity,
    required this.ownerId,
    this.priceSelected,
    this.productTypeList,
  });

  List<num>? get priceRange =>
      productTypeList?.map((e) => e.price ?? 0).toList() ?? [];

  // num
  String get priceStringDisplay => (productTypeList?.isEmpty ?? true) ||
          (priceRange?.isEmpty ?? true)
      ? ''.elseDisplay().prefixCurrency()
      : (priceRange?.length ?? false) == 1
          ? priceRange?.first.toString().prefixCurrency() ?? ''.elseDisplay()
          : '${priceRange?.first.prefixCurrency()} - ${priceRange?.last.prefixCurrency()}';

  num? get priceCurrentSelected =>
      (productTypeList
              ?.where((mapEntry) => mapEntry.id == priceSelected)
              .firstOrNull
              ?.price ??
          0) *
      (quantity ?? 0);

  factory Product.fromJson(Map<String, dynamic> json) =>
      _$ProductFromJson(json);

  Map<String, dynamic> toJson() => _$ProductToJson(this);

  Product copyWith({
    String? id,
    String? name,
    String? description,
    Map<String, num>? priceCategories,
    String? category,
    String? brand,
    List<String>? imageDetail,
    String? imageThumbnail,
    Map<String, dynamic>? attributes,
    List<String>? tag,
    String? image,
    String? imageName,
    String? storeId,
    num? quantity,
    String? ownerId,
    ProductStatus? status,
    String? priceSelected,
    List<ProductType>? productType,
  }) {
    return Product(
      id: id ?? this.id,
      name: name ?? this.name,
      description: description ?? this.description,
      // priceCategories: priceCategories ?? this.priceCategories,
      category: category ?? this.category,
      brand: brand ?? this.brand,
      imagesPath: imageDetail ?? this.imagesPath,
      imageThumbnail: imageThumbnail ?? this.imageThumbnail,
      attributes: attributes ?? this.attributes,
      tag: tag ?? this.tag,
      storeId: storeId ?? this.storeId,
      quantity: quantity ?? this.quantity,
      ownerId: ownerId ?? this.ownerId,
      status: status ?? this.status,
      priceSelected: priceSelected ?? this.priceSelected,
      productTypeList: productType ?? this.productTypeList,
    );
  }
}

@HiveType(typeId: 2)
enum ProductStatus {
  @HiveField(0)
  active,
  @HiveField(1)
  inactive,
  @HiveField(2)
  discontinued,
  @HiveField(3)
  outOfStock,
  @HiveField(4)
  undefined;

  static ProductStatus fromString(String? value) {
    switch (value) {
      case 'active':
        return ProductStatus.active;
      case 'inactive':
        return ProductStatus.inactive;
      case 'discontinued':
        return ProductStatus.discontinued;
      case 'outOfStock':
        return ProductStatus.outOfStock;

      default:
        return ProductStatus.undefined;
    }
  }
}
