// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:hive/hive.dart';

import 'package:ez_shop_sync/src/data/dto/hive_object/member.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:ez_shop_sync/src/theme/app_theme.dart';
import 'package:json_annotation/json_annotation.dart';

part 'store.g.dart';

@HiveType(typeId: 3)
@JsonSerializable(explicitToJson: true)
class Store extends BaseHiveObject {
  @HiveField(7)
  String ownerId;

  @HiveField(8)
  String name;

  @HiveField(9)
  String? address;

  @HiveField(10)
  List<String>? phoneNumbers;

  @HiveField(11)
  String? email;

  @HiveField(12)
  String? website;

  @HiveField(13)
  String? description;

  @HiveField(14)
  List<String>? images;

  @HiveField(15, defaultValue: [])
  List<String>? tags;

  @HiveField(16, defaultValue: null)
  AppTheme? storeTheme;

  @HiveField(17, defaultValue: [])
  List<String>? categories;

  @HiveField(18, defaultValue: [])
  List<Member> members;

  Store({
    super.id,
    BaseHiveData? super.info,
    required this.ownerId,
    required this.name,
    this.address,
    this.phoneNumbers,
    this.email,
    this.website,
    this.description,
    this.images,
    this.tags,
    this.storeTheme,
    this.categories,
    required this.members,
  });

  factory Store.fromJson(Map<String, dynamic> json) => _$StoreFromJson(json);

  /// Connect the generated [_$PersonToJson] function to the `toJson` method.
  Map<String, dynamic> toJson() => _$StoreToJson(this);
}
