// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/branch.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/member.dart';
import 'package:ez_shop_sync/src/data/repository/base_hive_object.dart';
import 'package:ez_shop_sync/src/theme/app_theme.dart';
import 'package:flutter/foundation.dart';
import 'package:hive/hive.dart';
import 'package:json_annotation/json_annotation.dart';

part 'store.g.dart';

@HiveType(typeId: 3)
@JsonSerializable(explicitToJson: true)
class Store extends BaseHiveObject {
  @HiveField(3)
  String ownerId;

  @HiveField(4)
  String name;

  @HiveField(5)
  String? address;

  @HiveField(6)
  List<String>? phoneNumbers;

  @HiveField(7)
  String? email;

  @HiveField(8)
  String? website;

  @HiveField(9)
  String? description;

  @HiveField(10, defaultValue: null)
  String? imageUrl;

  @HiveField(11, defaultValue: null)
  String? imageCoverUrl;

  @HiveField(12, defaultValue: [])
  List<String>? tags;

  @HiveField(13, defaultValue: null)
  AppTheme? storeTheme;

  @HiveField(14, defaultValue: [])
  List<String>? categories;

  @HiveField(15, defaultValue: [])
  List<Member> members;

  @HiveField(16, defaultValue: [])
  List<String>? products;

  @HiveField(17, defaultValue: [])
  List<Branch>? branches;

  Store({
    super.id,
    BaseHiveData? super.info,
    required this.ownerId,
    required this.name,
    this.address,
    this.phoneNumbers,
    this.email,
    this.website,
    this.description,
    this.imageUrl,
    this.tags,
    this.storeTheme,
    this.categories,
    required this.members,
    this.products,
    this.branches,
    this.imageCoverUrl,
  });

  List<String> get memberIds => members.map((e) => e.uid).toList();

  factory Store.fromJson(Map<String, dynamic> json) => _$StoreFromJson(json);

  /// Connect the generated [_$PersonToJson] function to the `toJson` method.
  Map<String, dynamic> toJson() => _$StoreToJson(this);

  Store copyWith({
    String? ownerId,
    String? name,
    String? address,
    List<String>? phoneNumbers,
    String? email,
    String? website,
    String? description,
    String? imageUrl,
    String? imageCoverUrl,
    List<String>? tags,
    AppTheme? storeTheme,
    List<String>? categories,
    List<Member>? members,
    List<String>? products,
    List<Branch>? branches,
  }) {
    return Store(
      ownerId: ownerId ?? this.ownerId,
      name: name ?? this.name,
      address: address ?? this.address,
      phoneNumbers: phoneNumbers ?? this.phoneNumbers,
      email: email ?? this.email,
      website: website ?? this.website,
      description: description ?? this.description,
      imageUrl: imageUrl ?? this.imageUrl,
      imageCoverUrl: imageCoverUrl ?? this.imageCoverUrl,
      tags: tags ?? this.tags,
      storeTheme: storeTheme ?? this.storeTheme,
      categories: categories ?? this.categories,
      members: members ?? this.members,
      products: products ?? this.products,
      branches: branches ?? this.branches,
    );
  }

  @override
  bool operator ==(covariant Store other) {
    if (identical(this, other)) return true;

    return other.ownerId == ownerId &&
        other.name == name &&
        other.address == address &&
        listEquals(other.phoneNumbers, phoneNumbers) &&
        other.email == email &&
        other.website == website &&
        other.description == description &&
        other.imageUrl == imageUrl &&
        other.imageCoverUrl == imageCoverUrl &&
        listEquals(other.tags, tags) &&
        other.storeTheme == storeTheme &&
        listEquals(other.categories, categories) &&
        listEquals(other.members, members) &&
        listEquals(other.products, products) &&
        listEquals(other.branches, branches);
  }

  @override
  int get hashCode {
    return ownerId.hashCode ^
        name.hashCode ^
        address.hashCode ^
        phoneNumbers.hashCode ^
        email.hashCode ^
        website.hashCode ^
        description.hashCode ^
        imageUrl.hashCode ^
        imageCoverUrl.hashCode ^
        tags.hashCode ^
        storeTheme.hashCode ^
        categories.hashCode ^
        members.hashCode ^
        products.hashCode ^
        branches.hashCode;
  }
}
