// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';

class BaseRepoRequest<T> {
  final String storeId;
  final String userId;
  final String branchId;

  BaseHiveData? info;
  T data;

  BaseRepoRequest({required this.storeId, required this.userId, required this.branchId, this.info, required this.data});

  factory BaseRepoRequest.build(BaseRepoRequest request, T data) {
    return BaseRepoRequest(storeId: request.storeId, branchId: request.branchId, userId: request.userId, data: data);
  }

  BaseRepoRequest<NT> overide<NT>({required NT data}) {
    return BaseRepoRequest<NT>(storeId: storeId, userId: userId, branchId: branchId, info: info, data: data);
  }
}
