// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:ez_shop_sync/src/data/dto/hive_object/base_hive_data.dart';

class BaseRepoRequest<T> {
  final String? storeId;
  final String? userId;
  BaseHiveData? info;
  T data;

  BaseRepoRequest({required this.storeId, required this.userId, required this.data, this.info});

  factory BaseRepoRequest.build(BaseRepoRequest request, T data) {
    return BaseRepoRequest(storeId: request.storeId, userId: request.userId, data: data);
  }

  // factory CreateOrderRequest.fromJson(Map<String, dynamic> json) => _$CreateOrderRequestFromJson(json);

  // Map<String, dynamic> toJson() => _$CreateOrderRequestToJson(this);
}
