// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZuLsIs-FaChtn8lF0_V2ez-yuezS59jc',
    appId: '1:561366791403:web:89345ba17d071df533faae',
    messagingSenderId: '561366791403',
    projectId: 'ez-shop-98ded',
    authDomain: 'ez-shop-98ded.firebaseapp.com',
    storageBucket: 'ez-shop-98ded.firebasestorage.app',
    measurementId: 'G-W6SZN1JCMB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwiX-ix-gm7cIQKRcgyv7167CQWpV6LU',
    appId: '1:561366791403:android:759b3e2ad73ad70233faae',
    messagingSenderId: '561366791403',
    projectId: 'ez-shop-98ded',
    storageBucket: 'ez-shop-98ded.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj2w2WLC53niArN45uuYGptUF5j-tOk1c',
    appId: '1:561366791403:ios:aaf316d4ee6c959f33faae',
    messagingSenderId: '561366791403',
    projectId: 'ez-shop-98ded',
    storageBucket: 'ez-shop-98ded.firebasestorage.app',
    iosBundleId: 'com.taloengratp.ezshopsync.tests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj2w2WLC53niArN45uuYGptUF5j-tOk1c',
    appId: '1:561366791403:ios:52122a4b4834dbe733faae',
    messagingSenderId: '561366791403',
    projectId: 'ez-shop-98ded',
    storageBucket: 'ez-shop-98ded.firebasestorage.app',
    iosBundleId: 'com.example.ezShopSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZuLsIs-FaChtn8lF0_V2ez-yuezS59jc',
    appId: '1:561366791403:web:759dc2740098572833faae',
    messagingSenderId: '561366791403',
    projectId: 'ez-shop-98ded',
    authDomain: 'ez-shop-98ded.firebaseapp.com',
    storageBucket: 'ez-shop-98ded.firebasestorage.app',
    measurementId: 'G-2LHE13MZ7G',
  );
}