// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:easy_localization/easy_localization.dart';
import 'package:ez_shop_sync/res/generated/locale.g.dart';
import 'package:ez_shop_sync/src/models/screen_mode.dart';
import 'package:ez_shop_sync/src/widgets/layout/column_gap_widget.dart';
import 'package:ez_shop_sync/src/widgets/text_form_field/text_form_field_ui_widget.dart';
import 'package:flutter/material.dart';

class FormCreatePriceCetagoryWidgetArgrument {
  final String name;
  final String? desc;
  final num? price;
  final num? quantity;

  const FormCreatePriceCetagoryWidgetArgrument({
    this.name = '',
    this.desc,
    this.price,
    this.quantity,
  });
}

class FormCreatePriceCetagoryWidget extends StatefulWidget {
  final void Function({
    String name,
    num price,
    num quantity,
    String? desc,
  })? onChange;
  final ScreenMode screenMode;
  final FormCreatePriceCetagoryWidgetArgrument? model;
  const FormCreatePriceCetagoryWidget({
    super.key,
    this.onChange,
    required this.screenMode,
    this.model,
  });

  @override
  FormCreatePriceCetagoryWidgetState createState() => FormCreatePriceCetagoryWidgetState();
}

class FormCreatePriceCetagoryWidgetState extends State<FormCreatePriceCetagoryWidget> {
  final _textProductTypeNameInput = TextEditingController();
  final _textProductTypeDescInput = TextEditingController();
  final _textProductTypePriceInput = TextEditingController();
  final _textProductQuantityInput = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.end,
      children: [
        Expanded(
          child: ColumnGapWidget(
            gap: 8,
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormFieldUiWidget(
                readOnly: widget.screenMode == ScreenMode.display,
                textValue: widget.model?.name.toString() ?? '',
                controller: _textProductTypeNameInput,
                label: LocaleKeys.priceCategoryName.tr(),
                onChanged: (val) {
                  widget.onChange?.call(name: _textProductTypeNameInput.text);
                },
              ),
              TextFormFieldUiWidget(
                readOnly: widget.screenMode == ScreenMode.display,
                textValue: widget.model?.desc?.toString() ?? '',
                controller: _textProductTypeDescInput,
                label: LocaleKeys.description.tr(),
                onChanged: (val) {
                  widget.onChange?.call(desc: _textProductTypeDescInput.text);
                },
              ),
              TextFormFieldUiWidget(
                readOnly: widget.screenMode == ScreenMode.display,
                textValue: widget.model?.price?.toString() ?? '',
                controller: _textProductTypePriceInput,
                keyboardType: TextInputType.number,
                label: LocaleKeys.price.tr(),
                onChanged: (value) {
                  widget.onChange?.call(price: num.tryParse(_textProductTypePriceInput.text) ?? 0);
                },
              ),
              TextFormFieldUiWidget(
                readOnly: widget.screenMode == ScreenMode.display,
                textValue: widget.model?.quantity?.toString() ?? '',
                controller: _textProductQuantityInput,
                label: LocaleKeys.optionalField.tr(args: [LocaleKeys.quantity.tr()]),
                keyboardType: TextInputType.number,
                onChanged: (value) {
                  widget.onChange?.call(quantity: num.tryParse(_textProductQuantityInput.text) ?? 0);
                },
              ),
            ],
          ),
        ),
        const SizedBox(
          width: 8,
        ),
      ],
    );
  }
}
