// ignore_for_file: public_member_api_docs, sort_constructors_first
// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:equatable/equatable.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product.dart';
import 'package:ez_shop_sync/src/data/dto/hive_object/product_type.dart';
import 'package:ez_shop_sync/src/models/screen_mode.dart';

abstract class CreateProductState extends Equatable {
  const CreateProductState() : super();

  @override
  List<Object?> get props => [];
}

class CreateProductInitial extends CreateProductState {
  @override
  String toString() => 'CreateProductInitial';
}

class CreateProductLoading extends CreateProductState {
  @override
  String toString() => 'CreateProductLoading';
}

class CreateProductUpdateSuccess extends CreateProductState {
  final Product? product;

  CreateProductUpdateSuccess(this.product);
  @override
  String toString() => 'CreateProductUpdateSuccess $product';

  @override
  List<Object?> get props => [product];
}

class CreateProductUpdateFailure extends CreateProductState {
  @override
  String toString() => 'CreateProductUpdateFailure';
}

class CreateProductAddCustomField extends CreateProductState {
  final String name;
  final String value;

  const CreateProductAddCustomField(this.name, this.value);

  @override
  String toString() => 'CreateProductAddCustomField(name: $name, value: $value)';

  @override
  List<Object?> get props => [name, value];
}

class CreateProductRemoveCustomField extends CreateProductState {
  final String name;

  const CreateProductRemoveCustomField(this.name);

  @override
  String toString() => 'CreateProductAddCustomField(name: $name)';

  @override
  List<Object?> get props => [name];
}

class CreateProductSuccess extends CreateProductState {
  final Product? product;

  const CreateProductSuccess(this.product);

  @override
  String toString() => 'CreateProductSuccess $product';

  @override
  List<Object?> get props => [product?.id];
}

class CreateProductUpdateProductType extends CreateProductState {
  final ProductType productType;

  const CreateProductUpdateProductType({required this.productType});
  @override
  String toString() => 'CreateProductUpdateProductType $productType';

  @override
  List<Object?> get props => [productType];
}

class CreateProductFailure extends CreateProductState {
  @override
  String toString() => 'CreateProductFailure';
}

class CreateProductProductTypeFailure extends CreateProductState {
  String? message;

  CreateProductProductTypeFailure(this.message);

  @override
  String toString() => 'CreateProductProductTypeFailure $message';

  @override
  List<Object?> get props => [message];
}

class CreateProductUpdateImages extends CreateProductState {
  final List<String>? imagesPath;

  const CreateProductUpdateImages(this.imagesPath);

  @override
  String toString() => 'CreateProductUpdateImages $imagesPath';

  @override
  List<Object?> get props => [imagesPath];
}

class ProductEditArgrument extends CreateProductState {
  final Product? product;
  final ScreenMode screenMode;
  const ProductEditArgrument({this.product, required this.screenMode});

  @override
  String toString() => 'ProductEditArgrument(product: $product, screenMode: $screenMode)';
  @override
  List<Object?> get props => [product?.id, screenMode];
}

class ProductScreenModeChange extends CreateProductState {
  final ScreenMode mode;

  const ProductScreenModeChange(this.mode);

  @override
  String toString() => 'ProductScreenModeChange $mode';
}

class CreateProductUpdateCategorySelect extends CreateProductState {
  final String name;

  const CreateProductUpdateCategorySelect(this.name);

  @override
  String toString() => 'ProductScreenModeChange $name';
}

class CreateProductUpdateTagsSelect extends CreateProductState {
  final List<String> names;

  const CreateProductUpdateTagsSelect(this.names);

  @override
  String toString() => 'CreateProductUpdateTagsSelect $names';
}

class CreateProductRefresh extends CreateProductState {
  final dynamic value;

  const CreateProductRefresh(this.value);
  @override
  String toString() => 'CreateProductRefresh $value';

  @override
  List<Object?> get props => [value];
}
